T: { value: 300.0, unit: kelvin }
P: { value: 101325, unit: Pa }
composition:
  O2: { value: 0.233, unit: dimensionless }
  N2: { value: 0.755, unit: dimensionless }
  Ar: { value: 0.013, unit: dimensionless }
  CO2: { value: 0.0006, unit: dimensionless }
  H2O: { value: 0.0, unit: dimensionless }
