HX_1:
  kind: "single_tube"
  pool_boiling: true
  inner_diameter: { value: 1.4, unit: m }
  inner_length: { value: 5.276, unit: m }
  wall:
    thickness: { value: 0.02, unit: m }
    conductivity: { value: 50, unit: W/m/K }
    surfaces:
      inner:
        roughness: { value: 50, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0001, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }
      outer:
        roughness: { value: 20, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0001, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }

  K:
    hot_inlet: 0.5
    hot_outlet: 0.0
    hot_bend: 0.0

    cold_inlet: 0.0
    cold_outlet: 0.0
    cold_bend: 0.0
HX_2:
  kind: "reversal_chamber"
  pool_boiling: true
  inner_diameter: { value: 1.6, unit: m }
  inner_length: { value: 0.8, unit: m }
  curvature_radius: { value: 0.8, unit: m }
  wall:
    thickness: { value: 0.02, unit: m }
    conductivity: { value: 50, unit: W/m/K }
    surfaces:
      inner:
        roughness: { value: 50, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0001, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }
      outer:
        roughness: { value: 20, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0001, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }

  K:
    hot_inlet: 0.0
    hot_outlet: 0.0
    hot_bend: 0.3

    cold_inlet: 0.0
    cold_outlet: 0.0
    cold_bend: 0.0
HX_3:
  kind: "tube_bank"
  pool_boiling: true
  inner_diameter: { value: 0.076, unit: m }
  inner_length: { value: 4.975, unit: m }
  tubes_number: { value: 118, unit: dimensionless }
  arrangement: "staggered"
  N_rows: { value: 6, unit: dimensionless }
  ST: { value: 0.11, unit: m }
  SL: { value: 0.11, unit: m }
  baffle_spacing: { value: 0.45, unit: m }
  baffle_cut: { value: 0.25, unit: dimensionless }
  bundle_clearance: { value: 0.010, unit: m }
  wall:
    thickness: { value: 0.0029, unit: m }
    conductivity: { value: 50, unit: W/m/K }
    surfaces:
      inner:
        roughness: { value: 50, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0001, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }
      outer:
        roughness: { value: 20, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0001, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }

  K:
    hot_inlet: 0.5
    hot_outlet: 1.0
    hot_bend: 0.0

    cold_inlet: 0.0
    cold_outlet: 0.0
    cold_bend: 0.0

HX_4:
  kind: "reversal_chamber"
  pool_boiling: true
  inner_diameter: { value: 1.6, unit: m }
  inner_length: { value: 0.8, unit: m }
  curvature_radius: { value: 0.8, unit: m }
  wall:
    thickness: { value: 0.02, unit: m }
    conductivity: { value: 50, unit: W/m/K }
    surfaces:
      inner:
        roughness: { value: 50, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0001, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }
      outer:
        roughness: { value: 20, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0001, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }

  K:
    hot_inlet: 0.0
    hot_outlet: 0.0
    hot_bend: 0.3

    cold_inlet: 0.0
    cold_outlet: 0.0
    cold_bend: 0.0

HX_5:
  kind: "tube_bank"
  pool_boiling: true
  inner_diameter: { value: 0.076, unit: m }
  inner_length: { value: 5.620, unit: m }
  tubes_number: { value: 100, unit: dimensionless }
  arrangement: "staggered"
  N_rows: { value: 6, unit: dimensionless }
  ST: { value: 0.11, unit: m }
  SL: { value: 0.11, unit: m }
  baffle_spacing: { value: 0.45, unit: m }
  baffle_cut: { value: 0.25, unit: dimensionless }
  bundle_clearance: { value: 0.010, unit: m }
  wall:
    thickness: { value: 0.0029, unit: m }
    conductivity: { value: 50, unit: W/m/K }
    surfaces:
      inner:
        roughness: { value: 50, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0001, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }
      outer:
        roughness: { value: 20, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0001, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }

  K:
    hot_inlet: 0.5
    hot_outlet: 1.0
    hot_bend: 0.0

    cold_inlet: 0.0
    cold_outlet: 0.0
    cold_bend: 0.0

HX_6:
  kind: "economiser"
  pool_boiling: false
  inner_diameter: { value: 0.0337, unit: m }
  tube_length: { value: 80, unit: m }
  n_tubes: { value: 120, unit: dimensionless }
  arrangement: "staggered"
  N_rows: { value: 26, unit: dimensionless }
  ST: { value: 0.075, unit: m }
  SL: { value: 0.08, unit: m }
  baffle_spacing: { value: 0.25, unit: m }
  baffle_cut: { value: 0.25, unit: dimensionless }
  bundle_clearance: { value: 0.010, unit: m }
  wall:
    thickness: { value: 0.0026, unit: m }
    conductivity: { value: 50, unit: W/m/K }
    surfaces:
      inner:
        roughness: { value: 20, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }
      outer:
        roughness: { value: 50, unit: micrometer }
        emissivity: { value: 0.80, unit: dimensionless }
        fouling_thickness: { value: 0.0, unit: m }
        fouling_conductivity: { value: 0.20, unit: W/m/K }
  shell_inner_diameter: { value: 0.95, unit: m } # Gas side

  K:
    hot_inlet: 0.5
    hot_outlet: 1.0
    hot_bend: 0.0

    cold_inlet: 0.5
    cold_outlet: 1.0
    cold_bend: 0.3
